Plantilla/Plantilla/Models/ErrorViewModel.cs
namespace Plantilla.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Plantilla/Plantilla/Models/Marca.cs
using System;
using System.Collections.Generic;

namespace Plantilla.Models
{
    public partial class Marca
    {
        public Marca()
        {
            Productos = new HashSet<Producto>();
        }

        public int Id { get; set; }
        public string? Nombre { get; set; }
        public bool? Estado { get; set; }

        public virtual ICollection<Producto> Productos { get; set; }
    }
}

Plantilla/Plantilla/Models/Producto.cs
using System;
using System.Collections.Generic;

namespace Plantilla.Models
{
    public partial class Producto
    {
        public int Id { get; set; }
        public string? Nombre { get; set; }
        public bool? Estado { get; set; }
        public int? IdMarca { get; set; }

        public virtual Marca? Marca { get; set; }
    }
}

Plantilla/Plantilla/Models/ViewModel/ProductoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Plantilla.Models.ViewModel
{
    public class ProductoViewModel
    {
        [Required]
        [Display (Name = "Nombre")]
        public string Nombre { get; set; }

        [Required]
        public int IdMarca { get; set; }
    }
}

Plantilla/Plantilla/Models/plantillaContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Plantilla.Models
{
    public partial class plantillaContext : DbContext
    {
        public plantillaContext()
        {
        }

        public plantillaContext(DbContextOptions<plantillaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Marca> Marcas { get; set; } = null!;
        public virtual DbSet<Producto> Productos { get; set; } = null!;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Server=SPE-P1TEC-06\\MSSQLSERVER01;Database=plantilla;Trusted_Connection=True;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Marca>(entity =>
            {
                entity.ToTable("marca");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Estado).HasColumnName("estado");

                entity.Property(e => e.Nombre)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("nombre");
            });

            modelBuilder.Entity<Producto>(entity =>
            {
                entity.ToTable("producto");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Estado).HasColumnName("estado");

                entity.Property(e => e.IdMarca).HasColumnName("idMarca");

                entity.Property(e => e.Nombre)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("nombre");

                entity.HasOne(d => d.Marca)
                    .WithMany(p => p.Productos)
                    .HasForeignKey(d => d.IdMarca)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_marca_producto");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

Plantilla/Plantilla/Controllers/ApiProductosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Plantilla.Models;

namespace Plantilla.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ApiProductosController : ControllerBase
    {
        private readonly plantillaContext _context;

        public ApiProductosController(plantillaContext context)
        {
            _context = context;
        }

        public async Task<List<Producto>> Get()
       => await _context.Productos.ToListAsync();

    }
}

Plantilla/Plantilla/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Plantilla.Models;
using System.Diagnostics;

namespace Plantilla.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Plantilla/Plantilla/Controllers/MarcaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Plantilla.Models;

namespace Plantilla.Controllers
{
    public class MarcaController : Controller
    {
        private readonly plantillaContext _context;

        public MarcaController(plantillaContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
            
            => View(await _context.Marcas.ToListAsync());
       
    }
}

Plantilla/Plantilla/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Plantilla.Models;
using Plantilla.Models.ViewModel;

namespace Plantilla.Controllers
{
    public class ProductoController : Controller
    {
        private readonly plantillaContext _context;

        public ProductoController(plantillaContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var productos = _context.Productos.Include(m => m.Marca);
            return View( await productos.ToListAsync());
        }

        public IActionResult Create()
        {
            ViewData["Marcas"] = new SelectList(_context.Marcas,"Id","Nombre");
                return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductoViewModel pro)
        {
            if (ModelState.IsValid)
            {
                var producto = new Producto()
                {
                    Nombre = pro.Nombre,
                    Estado = true,
                    IdMarca = pro.IdMarca,
                };
                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Marcas"] = new SelectList(_context.Marcas, "Id", "Nombre", pro.IdMarca);
            return View(pro);
        }


    }
}

Plantilla/Plantilla/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Plantilla/Plantilla/Views/Marca/Index.cshtml
@model List<Plantilla.Models.Marca>
<h1>MARCAS</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                Nombre
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var marca in Model){
            <tr>
                <th>
                    @Html.DisplayFor(m=>marca.Nombre)
                </th>
            </tr>
        }
       
    </tbody>
</table>

Plantilla/Plantilla/Views/Producto/Create.cshtml
@using Plantilla.Models.ViewModel
@model ProductoViewModel

<h1>
    Crear Producto
</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">

            <div asp-validation-summary="ModelOnly" class="text-danger">
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdMarca" class="control-label"></label>
               <select asp-for="IdMarca" class="form-control" asp-items="ViewBag.Marcas"></select>
                <span asp-validation-for="IdMarca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary"/>
                </div>
        </form>

    </div>
</div>

            @section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
            }

Plantilla/Plantilla/Views/Producto/Index.cshtml
@model List<Producto>

    <h1>Productos</h1>
    <p>
        <a asp-action="Create">
            Crear
        </a>
    </p>
    <table>
        <thead>
            <tr>
            <th>
                Producto
            </th>
                <th>
                    Marca
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach(var producto in Model){
                <tr>
                    <td>
                        @Html.DisplayFor(p=>producto.Nombre)
                    </td>
                <td>
                    @Html.DisplayFor(p=>producto.Marca.Nombre)
                </td>
                <td>

                </td>
                </tr>
            }
        </tbody>

    </table>

Plantilla/Plantilla/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Plantilla</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Plantilla.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Plantilla</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Marca" asp-action="Index">Marca</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Plantilla - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>